name: Matrix Test Workflow

on:
  workflow_dispatch: # Allows us to run it manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is the build job, it runs first."

  test:
    runs-on: ubuntu-latest
    needs: build # This job depends on the 'build' job
    strategy:
      matrix:
        # This matrix will create 3x2=6 parallel test jobs
        python-version: [3.9, 3.10, 3.11]
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Test on ${{ matrix.os }} with Python ${{ matrix.python-version }}
        run: echo "Testing on ${{ matrix.os }} with Python ${{ matrix.python-version }}"

  deploy:
    runs-on: ubuntu-latest
    needs: test # This job depends on all the matrix 'test' jobs completing
    steps:
      - run: echo "This is the deploy job, it runs last."