name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo "Build job is running!"

  test:
    runs-on: ubuntu-latest
    needs: build  # This job depends on the 'build' job
    steps:
      - name: Run a test script
        run: echo "Test job is running!"

  deploy:
    runs-on: ubuntu-latest
    needs: test # This job depends on the 'test' job
    steps:
      - name: Deploy step
        run: echo "Deploying the application!"